apiVersion: v1
kind: Service
metadata:
  name: pycondemo-feast-server
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.feastServer.service.type }}
  ports:
    - port: {{ .Values.feastServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pycondemo
    component: feast-server 